#PBS -N Sim4200groups1
#PBS -o /home/juank/Documents/Doctorado/Investigacion/uranus.uc3m.es/PBS/matrix4200-RS/runs/num_groups1/Sim4200groups1.o
#PBS -e /home/juank/Documents/Doctorado/Investigacion/uranus.uc3m.es/PBS/matrix4200-RS/runs/num_groups1/Sim4200groups1.e
#PBS -m abe -M jlaria@est-econ.uc3m.es
#PBS -l nodes=16,walltime=48:00:00

cd /home/juank/Documents/Doctorado/Investigacion/uranus.uc3m.es/PBS/matrix4200-RS/runs/num_groups1/
~/miniconda2/bin/R  CMD BATCH run.R
